# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3174a935308c3abb4d7b96bf81fcf9c85b8fd6954c44d27cbe1c2fc2091f2fb840cba033c8f2335427daeaef68431a8bd7e5f3fec5dd57af905f8eb265c9031

test:
  secret_key_base: dea13cb411faa3c061988d5fec2f40166352039fbce72c89784a40dace43f0d93e49cf71e2dc31afc80373675e355ba6255e7e764a10723a81c2a1b8a1da6d6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
