# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fcd1f0eeae26d315583121092c6cc3b8181f2c2da1e94f0ece082a46b725a9b84685d48d85b85aec59ab8092414f6e807eda0aa4e5f584d6ad58419b4111788

test:
  secret_key_base: 35824d47a500c482f0ba1b0a3938341487fc87701389a60a31cf4a782ed718468526c3ad76ab9e0e3bdaecb8ef6f683a1ecd3f1306c94062ab7a1f8c86d37640

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
