# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d3bf55016f889ea24b526727a19bbef4c2c1e3d3c560d24d38d7f1539391acdeada49e2afb41c3731ca276b8866a532099fabb7ae1fcf7ded444fff81ef3354

test:
  secret_key_base: 17d0262568f136c410f79ea71adf907c308146c6f7a47bd19e3619a0863598fa77e374800eb2c46308ef01d24189a8e99548a360de01ed8b82c80614f2fd576b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
